// apps/board/src/components/LanguageSelector.vue
<script setup lang="ts">
import { ref } from 'vue'
import { useI18n } from 'vue-i18n'
import { setLocale } from '@/i18n/i18n'
import type { Locale } from '@/i18n/i18n'

const { locale } = useI18n()

const LANGUAGES: { key: Locale; country: string; label: string; nativeName: string }[] = [
  { key: 'cs', country: 'cz', label: 'Czech',   nativeName: 'Čeština' },
  { key: 'en', country: 'gb', label: 'English',  nativeName: 'English' },
  { key: 'de', country: 'de', label: 'German',   nativeName: 'Deutsch' },
  { key: 'es', country: 'es', label: 'Spanish',  nativeName: 'Español' },
  { key: 'fr', country: 'fr', label: 'French',   nativeName: 'Français' },
  { key: 'sv', country: 'se', label: 'Swedish',  nativeName: 'Svenska' },
]

const open = ref(false)

function select(key: Locale) {
  setLocale(key)
  open.value = false
}
</script>

<template>
  <div class="relative">
    <button
      type="button"
      class="flex items-center gap-1.5 px-2 py-1.5 rounded border border-gray-200 bg-gray-50 hover:bg-gray-100 text-sm text-gray-700 transition-colors w-full"
      @click.stop="open = !open"
    >
      <span class="i-mdi-translate w-4 h-4 shrink-0 text-gray-500" />
      <span class="flex-1 text-left">
        {{ LANGUAGES.find(l => l.key === locale)?.label }}
        <span class="text-gray-400 ml-1 text-xs">{{ LANGUAGES.find(l => l.key === locale)?.nativeName }}</span>
      </span>
      <span
        class="i-mdi-chevron-down w-4 h-4 shrink-0 text-gray-400 transition-transform"
        :class="{ 'rotate-180': open }"
      />
    </button>

    <div
      v-if="open"
      class="absolute z-50 left-0 right-0 mt-1 bg-white border border-gray-200 rounded-lg shadow-lg py-1"
    >
      <button
        v-for="lang in LANGUAGES"
        :key="lang.key"
        type="button"
        class="flex items-center gap-3 w-full px-3 py-2 text-sm hover:bg-gray-50 transition-colors"
        :class="locale === lang.key ? 'bg-gray-50' : ''"
        @click.stop="select(lang.key)"
      >
        <span :class="`fi fi-${lang.country} fis`" class="shrink-0 rounded-sm w-5 h-5 object-cover" style="font-size: 1.25rem" />
        <span class="flex flex-col flex-1 min-w-0 text-left">
          <span class="font-medium text-gray-900" :class="{ 'text-blue-600': locale === lang.key }">{{ lang.label }}</span>
          <span class="text-xs text-gray-400">{{ lang.nativeName }}</span>
        </span>
        <span v-if="locale === lang.key" class="i-mdi-check w-4 h-4 text-blue-500 shrink-0" />
      </button>
    </div>
  </div>

  <div v-if="open" class="fixed inset-0 z-40" @click="open = false" />
</template>

// apps/client/src/components/molecules/LanguageSelector.tsx
import { Check, Languages } from 'lucide-react';
import { useTranslation } from 'react-i18next';

import {
  DropdownMenu,
  DropdownMenuContent,
  DropdownMenuItem,
  DropdownMenuLabel,
  DropdownMenuSeparator,
  DropdownMenuTrigger,
} from '@/components/ui/dropdown-menu';
import { cn } from '@/lib/utils';
import { Button, FlagIcon } from '../atoms';

type Language = {
  key: string;
  country: string;
  label: string;
  nativeName?: string;
};

const LANGUAGES: Language[] = [
  {
    key: 'cs',
    country: 'cz',
    label: 'Czech',
    nativeName: 'Čeština',
  },
  {
    key: 'en',
    country: 'gb',
    label: 'English',
    nativeName: 'English',
  },
  {
    key: 'de',
    country: 'de',
    label: 'German',
    nativeName: 'Deutsch',
  },
  {
    key: 'es',
    country: 'es',
    label: 'Spanish',
    nativeName: 'Español',
  },
  {
    key: 'fr',
    country: 'fr',
    label: 'French',
    nativeName: 'Français',
  },
  {
    key: 'sv',
    country: 'se',
    label: 'Swedish',
    nativeName: 'Svenska',
  },
];

export const LanguageSelector = () => {
  const { i18n, t } = useTranslation();

  // Fallback if no language is specified
  if (LANGUAGES.length === 0) {
    console.warn('No languages configured for LanguageSelector');
    return null;
  }

  const current = i18n.resolvedLanguage ?? i18n.language;

  const handleChange = async (value: string) => {
    try {
      await i18n.changeLanguage(value);
    } catch (error) {
      console.error('Failed to change language:', error);
    }
  };

  return (
    <DropdownMenu>
      <DropdownMenuTrigger asChild>
        <Button
          variant="ghost"
          size="icon"
          className="w-9 h-9 relative group"
          title={t(
            'Molecules.LanguageSelector.SelectLanguage',
            'Select language'
          )}
        >
          <Languages className="h-4 w-4 transition-transform group-hover:scale-110" />
          <span className="sr-only">
            {t('Molecules.LanguageSelector.SelectLanguage', 'Select language')}
          </span>
        </Button>
      </DropdownMenuTrigger>

      <DropdownMenuContent align="end" className="w-56" sideOffset={8}>
        <DropdownMenuLabel className="flex items-center gap-2">
          <Languages className="h-4 w-4" />
          {t('Molecules.LanguageSelector.Title', 'Language')}
        </DropdownMenuLabel>
        <DropdownMenuSeparator />

        {LANGUAGES.map(lang => {
          const isSelected = current === lang.key;

          return (
            <DropdownMenuItem
              key={lang.key}
              onClick={() => handleChange(lang.key)}
              className={cn(
                'flex items-center gap-3 cursor-pointer py-2',
                isSelected && 'bg-accent'
              )}
            >
              {/* Flag and language info */}
              <div className="flex items-center gap-3 flex-1 min-w-0">
                <FlagIcon
                  countryCode={lang.country}
                  size="sm"
                  className={cn(
                    'shrink-0 transition-transform',
                    isSelected && 'scale-110'
                  )}
                />

                <div className="flex flex-col min-w-0 flex-1">
                  <span
                    className={cn(
                      'text-sm font-medium truncate',
                      isSelected && 'text-primary font-semibold'
                    )}
                  >
                    {lang.label}
                  </span>
                  {lang.nativeName && (
                    <span className="text-xs text-muted-foreground truncate">
                      {lang.nativeName}
                    </span>
                  )}
                </div>
              </div>

              {/* Checkmark for selected language */}
              {isSelected && (
                <Check className="h-4 w-4 text-primary shrink-0" />
              )}
            </DropdownMenuItem>
          );
        })}
      </DropdownMenuContent>
    </DropdownMenu>
  );
};

export default LanguageSelector;
